CREATE TABLE [dbo].[House](
		[Id] [nvarchar](15) NOT NULL,
		[Name] [nvarchar](50) NOT NULL,
		[Address] [nvarchar](200) NULL,
	 CONSTRAINT [PK_House] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]