CREATE TABLE [dbo].[OrderCustomer](
		[OrderId] nvarchar(15) NOT NULL,
		[CustomerId] nvarchar(15) NOT NULL
	 CONSTRAINT [PK_OrderCustomer] PRIMARY KEY CLUSTERED 
	(
		[OrderId] ASC,
		[CustomerId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]