CREATE TABLE [dbo].[OrderRoom](
		[OrderId] nvarchar(15) NOT NULL,
		[RoomId] nvarchar(15) NOT NULL
	 CONSTRAINT [PK_OrderRoom] PRIMARY KEY CLUSTERED 
	(
		[OrderId] ASC,
		[RoomId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]